language: node_js
node_js:
  - "7"

install:
  - npm install -g mocha
  - npm install
  
script:
  - npm run test


deploy:
  provider: npm
  email: 1245712564@qq.com
  api_key: $NPM_TOKEN
  on:
    tags: true
